### PR TITLE
Add ability to sort columns

### LINKED ISSUE #3: Sort and filtering of columns
I know that sorting is not currently supported. Do you have any instructions about how can this be achieved, would you say that this is a driver issue or a flipper issue?

Also any info about filtering on columns cause it appears that there is a bug when filtering out a column

Thanks in advance

### PR DESCRIPTION
**Pull request by pstens**
This resolves #3

### CODE REVIEW

**Comment by kamgurgul** [comment]
It will fail for STRING_LIST
image
You can verify it on Test2 table.

**Comment by pstens** [comment]
> It will fail for STRING_LIST

This is actually a limitation in Realm's `QueryDescriptor` as it does not only support sorting for the following types:

image

I feel like there's not much we can do here besides catching the exception and displaying something more meaningful to the user.

Anyways, how would you compare different list rows; by sorting the list first, and then doing a comparison on the first element of each list? Or would you just compare the number of elements?

**Comment by kamgurgul** [comment]
The only thing which can be done here is to ignore sorting of unsupported types. We cannot throw errors because it will crash Flipper session.

**Comment by kamgurgul** [comment]
Closing because lack of activity

**Pull request closed without merging**
